### ISSUE TITLE
Extracting data from different site collection

### ISSUE THREAD

**Issue by illuminator999** [samperrow/SPCalendarPro#16]
Thanks for this solution! I've been searching for something like this for at least a year. Question, how do I configure it to extract data from a calendar in a different site collection?

**Comment by samperrow** [comment]
Thank you for the kind words, I hope this lib makes your life easier. 

I have not tried to make requests to other SC's with this before, I will take a look and see how and if this can be done. Good suggestion.

If you notice any bugs, please let me know about them so I can put in a fix. I cannot fix things that I am not aware of :)

**Comment by samperrow** [comment]
Actually you can use the `sourceSite` property and specify the URL from the other SC, and it works just fine. The same applies if you want to grab data from other sites as well.
